/*
 * profiling.h
 *
 *  Created on: Oct 27, 2021
 *      Author: AUTHOR_NAME_REMOVED
 */

#ifndef INC_PROFILING_H_
#define INC_PROFILING_H_

#define MACRO_EVALUATION
//#define PROFILE

#define PROF_PORT GPIOD
#define PROF_POINT_NS_LOOP_START 1
#define PROF_POINT_NS_NEW_DATA 2
#define PROF_POINT_NS_IDLE_START 3
#define PROF_POINT_NS_NEWDATA_START 4
#define PROF_POINT_NS_NEWDATA_END 5
#define PROF_POINT_NS_ACQUIRE_MEL_ENTRY 6
#define PROF_POINT_NS_PROCESS_NN_ENTRY 7
#define PROF_POINT_NS_RESULT_CHECK 8
#define PROF_POINT_NS_FULLACCESS_START 9
#define PROF_POINT_NS_FULLACCESS_END 10

#define PROF_POINT_ACQUIRE_MEL_START 64
#define PROF_POINT_ACQUIRE_MEL_END 65
#define PROF_POINT_PROCESS_NN_START 66
#define PROF_POINT_PROCESS_NN_END_KW 67
#define PROF_POINT_PROCESS_NN_END_NOKW 68
#define PROF_POINT_PROCESS_NN_INIT_START 69
#define PROF_POINT_PROCESS_NN_INIT_END 70
#define PROF_POINT_PROCESS_NN_RUN 71

#define PROF_POINT_NS_PROCESS_INIT_ENTRY 72

#define PROF_POINT_S_ENTRY_GW 128
#define PROF_POINT_S_GW_CALL_NS 129
#define PROF_POINT_S_GW_REENTRY 130
#define PROF_POINT_S_GW_LEAVE_IDLE 131
#define PROF_POINT_S_GW_LEAVE_FULLACCESS 132

#define PROF_POINT_S_TIMER_WAIT_START 133
#define PROF_POINT_S_TIMER_WAIT_END 134

#define PROF_POINT_S_WIPE_START 135
#define PROF_POINT_S_WIPE_END 136

#define PROF_POINT_DBG_1 200
#define PROF_POINT_DBG_2 201




#ifdef PROFILE
#define PROF_WRITE(x) ((PROF_PORT->ODR = x))
#else /* PROFILE */
#define PROF_WRITE(x)
#endif /* PROFILE */


#define MACRO_KW_DETECTED_Pin GPIO_PIN_5
#define MACRO_KW_DETECTED_GPIO_Port GPIOA
#define MACRO_WIPING_Pin GPIO_PIN_6
#define MACRO_WIPING_GPIO_Port GPIOA
#define MACRO_WORKING_Pin GPIO_PIN_7
#define MACRO_WORKING_GPIO_Port GPIOA
#define MACRO_DBG_1_GPIO_Port GPIOA
#define MACRO_DBG_1_Pin GPIO_PIN_8

#ifdef MACRO_EVALUATION
#define MACRO_SET_KW_DETECTED() ((MACRO_KW_DETECTED_GPIO_Port->BSRR = MACRO_KW_DETECTED_Pin))
#define MACRO_RESET_KW_DETECTED() ((MACRO_KW_DETECTED_GPIO_Port->BSRR = MACRO_KW_DETECTED_Pin << 16))

#define MACRO_SET_WIPING() ((MACRO_WIPING_GPIO_Port->BSRR = MACRO_WIPING_Pin))
#define MACRO_RESET_WIPING() ((MACRO_WIPING_GPIO_Port->BSRR = MACRO_WIPING_Pin << 16))

#define MACRO_SET_WORKING() ((MACRO_WORKING_GPIO_Port->BSRR = MACRO_WORKING_Pin))
#define MACRO_RESET_WORKING() ((MACRO_WORKING_GPIO_Port->BSRR = MACRO_WORKING_Pin << 16))

#define MACRO_SET_DEBUG_1() ((MACRO_DBG_1_GPIO_Port->BSRR = MACRO_DBG_1_Pin))
#define MACRO_RESET_DEBUG_1() ((MACRO_DBG_1_GPIO_Port->BSRR = MACRO_DBG_1_Pin << 16))
#else /* MACRO_EVALUATION */
#define MACRO_SET_KW_DETECTED()
#define MACRO_RESET_KW_DETECTED()

#define MACRO_SET_WIPING()
#define MACRO_RESET_WIPING()

#define MACRO_SET_WORKING()
#define MACRO_RESET_WORKING()

#define MACRO_SET_DEBUG_1()
#define MACRO_RESET_DEBUG_1()
#endif /* MACRO_EVALUATION */

#endif /* INC_PROFILING_H_ */
